### ISSUE TITLE
BrowserLink telemetry being sent to Azure

### ISSUE THREAD

**Issue by ppumkin** [Microsoft/ApplicationInsights-Home#122]
Browserlink shows up as a dependency AJAX and is flooding my charts while debugging.

I had a look at the 

`<Add Type="Microsoft.ApplicationInsights.Web.SyntheticUserAgentTelemetryInitializer, Microsoft.AI.Web">`

and 

`<Add Type="Microsoft.ApplicationInsights.Web.RequestTrackingTelemetryModule, Microsoft.AI.Web">`

but it is not entirely clear to me how to filter out browserLink from Visual Studio

I am currently evaluating on the free tier and I know I probably need to setup separate Azure Resources  but I really do not need to be sending and using data for browserlink any way. (especially when you have a large dev team) 

![image](https://cloud.githubusercontent.com/assets/1249683/26453609/405c12e8-415c-11e7-83e1-03bb22be7aaa.png)

**Comment by SergeyKanzhelev** [comment]
@gardnerjr how does Visual Studio picks up the AJAX dependencies? My understanding is that they are reported by JavaScript SDK and sent directly to portal. How the magic works?

@ppumkin I moved this issue to the JavaScript repository. You can probably implement a simple telemetry initializer that will filter those out.

**Comment by gardnerjr** [comment]
*visual studio* is not picking up the ajax dependencies while debugging.  That's a live search showing real data in this resource.  I can tell because it is showing "performance" as a field (performanceBucket) which is calculated by ingestion, not sent by the sdk (sdk sends duration)

There are a few possible things to do:
1. turn of browserlink if you don't need it - uncheck "enable browserlink" in the debug toolbar
2. write javascript code in your app to filter out browserlink dependencies

otherwise, the javascript sdk may need some easy way to filter out browserlink dependencies automatically.  (i thought it already had something for this?)

**Comment by SergeyKanzhelev** [comment]
Thanks @gardnerjr! Closing it in this repository and will wait the response in JavaScript SDK one...
