### ISSUE TITLE
Reset operator definition needs more clarity in experimental correlation spec

### ISSUE THREAD

**Issue by jacpull** [Microsoft/ApplicationInsights-Home#149]
The relationship between the Reset operator and the Hash is not clear. 

- Reset(X-Y) => X-Z: where Z = Base64Encode(RANDOM_8) // Does not use Hash
- Reset(X.Y) = X-Z:  where Z = Base64Encode(HASH_8("X.Y")) or should this be Base64Encode(HASH_8(".Y"))
- Reset(X-Y.Z) = X-P: where P = Base64Encode(HASH_8("X-Y.Z")) or should this be Base64Encode(HASH_8("-Y.Z"))
- Reset(X) = X-Z: where Z = Base64Encode(RANDOM_8) // Does not use Hash

Is this the intended definition?

@SergeyKanzhelev @vancem @lmolkova

**Comment by SergeyKanzhelev** [comment]
@jacpull  there is no hash operation. Only **Reset**. If you refer to the fallback option for unsupported format of `Span-base-ID` - **Reset** operation should be applied. The only need to hash the `<span-base-id>` and `<level>.<level>` is if it do not match expected size or characters set. In this case hashed value may be stored in vendors' backend, but it will not participate in any request id propagation

**Comment by SergeyKanzhelev** [comment]
I think you are trying to put an extra semantic into **Reset** operation. Or perhaps create a new **ResetHierarchy** operation. My believe that correlation protocol already has this characteristics that certain connections may be lost because the **Reset** is perfectly legit operation. Solving this particular problem of hierarchy **Reset** will not solve the overall issue.

I think we can put an appendix paragraph recommending to create `HASH_8(.2.4.6)` as an implementation detail for **Reset**. I haven't thought of it in details, but this implementation can be a standard for .NET. But I do not thing that it should be a part of the main spec.

Agree?

**Comment by jacpull** [comment]
I'm ok with an explicit recommendation to Hash_8(<span-base-id>.<level>..<level>) for the purposes of supporting back end inference.

**Comment by jacpull** [comment]
The recommendation should invoke the Hash on the span-base-id and vector parts, i.e. everything but the trace-id.
