### ISSUE TITLE
Snapshot collector and console applications

### ISSUE THREAD

**Issue by KenBrannigan** [microsoft/ApplicationInsights-Home#245]
Should the snapshot collector work in a console application?

I do get the exception logged but no snapshot ever appears. The portal doesn't even show the link to help troubleshoot snapshot issues that the documentation mentions.

**Comment by SergeyKanzhelev** [comment]
CC: @pharring

**Comment by pharring** [comment]
Yes, it'll work. It's pretty straightforward, but with console apps there's a variety of ways to set up Application Insights, so it's hard to give specific advice. Generally:
1. Add the Snapshot Collector's TelemetryProcessor to a telemetry pipeline (usually via the TelemetryProcessorChainBuilder -- there's an extension method in the SnapshotCollector assembly for that).
2. Call TrackException somewhere from a catch block or exception filter.

If it's set up correctly, you should see custom events for heartbeat and snapshotting activity.

A couple of common problems:
1) Snapshot Collector is disabled in "DeveloperMode" (i.e. when debugging in Visual Studio) by default. That can be overridden in code or via configuration.
2) Snapshots are collected (by default) on the 2nd (and subsequent) incidence of any given exception. The explanation for this is given in the documentation: https://docs.microsoft.com/azure/application-insights/app-insights-snapshot-debugger#how-snapshots-work

If you still can't get it to work, please supply more details about your app. e.g. .NET Framework or .NET Core? How are you configuring the telemetry pipeline (please share the code)?

**Comment by KenBrannigan** [comment]
Hey @pharring ,
Thanks for the response. Here is some additional details:

.NET Framework 4.5.1

All Microsoft.ApplicationInsights NuGet packages are v2.7.1 except for Agent.Intercetor which is v2.4.0 and SnapshotCollector which is v1.3.0.

We use a custom AppDomainManager to attach to the AppDomain.CurrentDomain.UnhandledException event.

In the UnhandledException event we have the following code:

`            
Exception exception = ((Exception)e.ExceptionObject);

Microsoft.ApplicationInsights.TelemetryClient telemetryClient = new Microsoft.ApplicationInsights.TelemetryClient();

telemetryClient.TrackException(exception);

telemetryClient.Flush();

System.Threading.Thread.Sleep(2000);

Environment.Exit(1);
`

I have attached our ApplicationInsights.config file which is where we are configuring the telemetry pipeline and where we are setting IsEnabledInDeveloperMode to true.

I am running the console applications multiple times to generate the same error so I can go over the minimum 1 exception threshold for a problem id.

I did try taking the line of code that I wrote that causes an exception and wrapped it in a try...catch and called the code above without the exit statement and then repeated that 3 times. I thought maybe the problem had to do with us exiting the console application and that the minimum 1 exception threshold was tied just to a single run of the console application but that never produced a snapshot either.

Thank you very much for your help I really appreciate it.

[ApplicationInsights.zip](https://github.com/Microsoft/ApplicationInsights-Home/files/2284263/ApplicationInsights.zip)

**Comment by KenBrannigan** [comment]
@pharring any update on this?

**Comment by pharring** [comment]
Thanks for the details and sorry for not replying sooner (I was on vacation). Unfortunately, SnapshotCollector isn't suitable for your UnhandledException scenario because all the "problem" counts are lost when the application exits -- just as you thought.

The ZIP file you attached includes only the ApplicationInsights.config file, so I can't see how you're initializing the pipeline, but I do see you've set IsEnabledInDeveloperMode -- that's good. Do you see custom events from the Snapshot Collector indicating that it is working? Heartbeat? When your console app is running do you also see "SnapshotUploader.exe" or "SnapshotUploader64.exe" running? That process will be launched once the SnapshotCollector's TelemetryProcessor has made connection with the Snapshot Debugger's service. That's an asynchronous operation triggered by the appearance of the first telemetry item through the pipeline with a valid instrumentation key. It can take a few seconds for our service to respond and the Snapshot Collector won't be enabled until it does. If your test sent the three exception telemetries very quickly, that may not have been enough time.

If you'd like, you can reach us at snapshothelp@microsoft.com and maybe we can help debug this over Skype.

**Comment by pharring** [comment]
Closing old issue.
