### ISSUE TITLE
App Insights end to end times do not match

### ISSUE THREAD

**Issue by imeya** [microsoft/ApplicationInsights-Home#268]
I have the similar issue which has been posted by others on stackoverflow here: https://stackoverflow.com/questions/52545874/app-insights-end-to-end-times-do-not-match .

![time](https://user-images.githubusercontent.com/25738099/46653404-859f8a80-cbd8-11e8-9e3c-104e44cf637f.JPG)

**Comment by lmolkova** [comment]
What kinds of external calls your app makes?

Please also provide: 
- ApplicationInsights version and flavor 
- .NET version and flavor
- how is it hosted (Azure Web App, Cloud service, VM, etc)
- ApplicationInsights.config if applicable (please strip secrets!)

Note, AppInsights tracks all kinds of Http calls, SQL calls ServiceBus and EventHub (depending on SDK version and flavor), it could be that your app makes calls we don't track: IO, Redis, MongoDb, TCP WCF  or TCP DocumentDb. We are working on extending the number of libs we collect, but we don't collect everything.

It might be that the server is too slow because of CPU/mem/IO bottleneck and time is spent internally. Please check related metrics.

**Comment by imeya** [comment]
how to check the app insights' flavor?

**Comment by lmolkova** [comment]
What kind of application do you have?
The easiest way is just to send us the list of ApplicationInsights nuget packages you've installed on the app.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
