### ISSUE TITLE
Tracking async HTTP dependencies in ASP.NET

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/ApplicationInsights-Home#27]
All of our async HTTP requests are reporting as taking microseconds to execute when they are actually taking 1-30 seconds.

```csharp
var address = new Uri("http://foo.bar");
var content = new StringContent("{'foo': 'bar'");
content.Headers.ContentType = new MediaTypeWithQualityHeaderValue("application/json");
var response = await new HttpClient().PostAsync(address, content);
```

Non-async HTTP requests have accurate timings.  This is on a server running IIS with the status monitor configured.

**Comment by SergeyKanzhelev** [comment]
Have you install Status Monitor or Azure WebSite extension? Or just using out of the box collection with the framework 4.6?

**Comment by gregjhogan** [comment]
The status monitor is installed and this is not a web app (on-prem IIS server).  SQL dependencies and performance counters are working perfectly.  Is measuring async HTTP calls supported?

**Comment by gregjhogan** [comment]
Also, I should have mentioned the code is compiled against .NET 4.5.1 and ASP.NET 4.6

**Comment by gregjhogan** [comment]
I just realized that I am using the pre-release ASP.NET libraries for AI.  I was on beta2 and I just upgraded to beta4.  I compared yesterday's AI data to today's, and it looks better, but still strange.  On beta2 every HTTP dependency was in the microsecond range, and there was one record per call.  On beta4 there are 1 to 3 records per actual HTTP call and one of the records appears to be an accurate elapsed time while the others are in the microsecond range.  Also, none of these records are time to an operation (like SQL dependencies are).

**Comment by SergeyKanzhelev** [comment]
@gregjhogan so you are saying that StatusMonitor installed, but it is not used as your application is not running in IIS. Than it's Framework instrumentation.

If you are running on FW 4.6 there are four methods being instrumented with EventSource:

```
BeginGetRequestStream
EndGetRequestStream
BeginGetResponse
EndGetResponse
```

Since `HttpClient` is a wrapper on top of `HttpWebRequest` in FW 4.6 - those EventSource messages will be used. `PostAsync` will send request as a stream first and than will start getting response. So it might send two dependency calls instead of one. However I don't understand how the time may not be accounted. How big is a server response? 

This logic wasn't changed between beta2 and beta4. And BTW, it's now open source. You can see an implementation of http tracking here: https://github.com/Microsoft/ApplicationInsights-server-dotnet/blob/master/Src/DependencyCollector/Shared/Implementation/HttpProcessingFramework.cs

Is it consistent with what you experience?

**Comment by gregjhogan** [comment]
@SergeyKanzhelev I haven't had time yet to step through what is happening in the AI libraries yet, but I was trying to indicate that I have the status monitor installed and it is running on IIS (on-prem, not in the cloud).  I believe that means it is not using ETW?

On beta4, the time does now seem to all be accounted for, but if there is often more than one telemetry event for each HTTP request.  All but one event are in the microsecond range and the remaining event seems to represent the majority of the request time (often 2 to 10 seconds and sometimes longer).  The server responses are somewhat large at times (10K+)

**Comment by SergeyKanzhelev** [comment]
We will be tracking this in server SDK repository
