### ISSUE TITLE
New experience, explain what settings you are applying

### ISSUE THREAD

**Issue by phatcher** [microsoft/ApplicationInsights-Home#312]
Got this today on one of web sites...

<img width="318" alt="ai extension" src="https://user-images.githubusercontent.com/192778/49932265-80083e80-fec0-11e8-9ce8-490114c9f158.PNG">

and when I press "Turn on site extension", I get the following

![image](https://user-images.githubusercontent.com/192778/49932442-eee59780-fec0-11e8-83e7-b004748789d4.png)

Couple of points...
1. I already had the latest version of the extension installed
2. It doesn't say (or link) to what application changes are going to be made, I want to know so I can automate the changes on the other sites I have.
3. The language implies that I'm not already hooked up even though my app is already configured and producing telemetry.

**Comment by phatcher** [comment]
Sorry just sway the "Application Insights is linked through Instrumentation key" value above - so what's the difference between that and "Turn on Site Extension"?

**Comment by SergeyKanzhelev** [comment]
@Mikhail-Pranovich please take a look

**Comment by cweining** [comment]
We retiring the current version of the application insights site extension and moving to a pre-installed extension. The new extension does not need to be installed – it is already part of the Azure App Service runtime. To enable AI, you just need to set a few app settings. You can turn on the new site extension for an application, then duplicate those app settings to turn it on for other applications.
 
When you click the “Yes” button on the web page you pasted above, it will uninstall the current App Insights site extension and add the app settings to enable the pre-installed site extension. To replicate that for your other sites, you would need to uninstall the site extension and set the same app settings. 
 
Both site extensions use an app setting containing the App Insights iKey to direct data to the proper instance of App Insights. There are other ways to link an app to App Insights, so that first phrase is just letting you know what method is being used. The “Turn On site extension” button will upgrade your site to use the new, pre-installed site extension.
