### ISSUE TITLE
Application Insights custom metrics: wrong data for Function Failures

### ISSUE THREAD

**Issue by spkrishnankutty** [microsoft/ApplicationInsights-Home#363]
The CustomMetrics for functioApp: - Failure, Success & Count on an aggregation over count, returns the same data. At the least the result set while looking for function app failed executions should be different from the total execution count.

The easiest way to reproduce this is to have an application inisghts hooked to a function app with a running funtion. Then head over to metrics and add custom metrics to graph for failure,success & count and you can see that the data is essentially the same.

**Comment by Dmitry-Matveev** [comment]
Most likely, the issue is pre-selected aggregation "Count". It will actually display the count of times the metric with this name those submitted rather than the aggregation on top of the value of the metric.

I just tried it out and as soon as I switched to "Sum" aggregation, the values started to make sense.

**Comment by Dmitry-Matveev** [comment]
@spkrishnankutty , feel free to re-open the issue if the explanation above does not fix the situation.

**Comment by spkrishnankutty** [comment]
@Dmitry-Matveev Yes, the aggregation over "Sum" gives proper results. Its the aggregation over "Count" that gives erroneous result.
