### ISSUE TITLE
Release Annotations for Azure Application Insights for Azure DevOps

### ISSUE THREAD

**Issue by HowardvanRooijen** [microsoft/ApplicationInsights-Home#376]
Is the source available for Release Annotations for Azure Application Insights for Azure DevOps: 

https://marketplace.visualstudio.com/items?itemName=ms-appinsights.appinsightsreleaseannotations

We're seeing a warning in our ADO logs:

`Task 'ms-appinsights.ReleaseAnnotation' (1.0.14) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib`

**Comment by MS-TimothyMothra** [comment]
@Dmitry-Matveev do you know who owns the "Application Insights Task" used in Azure DevOps?
We need to route this to that team.

**Comment by debugthings** [comment]
Thanks @HowardvanRooijen the extension is not out there, but I see what is happening. We are indeed using an older execution handler. It also seems as if this is is a recent change on the agents to check for this. Aside from the warning message it should not affect anything.

I'll test a fix by next week to see if it gets rid of this error message.

```
"execution": {
        "PowerShell": {
            "target": "$(currentDirectory)\\DeploymentMarker.ps1",
...
```

**Comment by HowardvanRooijen** [comment]
HI James,

That would be amazing. Thanks for supporting the extension. It's a shame it's not on GitHub as I would have happily worked on a fix.

Love release annotations - they are so useful!

Thanks!

Howard

**Comment by debugthings** [comment]
Hey @HowardvanRooijen I've updated the task to use the new PowerShellV3 module so that message should go away. The extension should update on the next run of a pipeline that has it. You can check to make sure you have the latest version (0.0.60) by navigating to one of the links below.



https://{{yourdevopsorgname}}.visualstudio.com/_settings/extensions?tab=installed&extension=ms-appinsights.appinsightsreleaseannotations

or

https://dev.azure.com/{{yourdevopsorgname}}/_settings/extensions?tab=installed&extension=ms-appinsights.appinsightsreleaseannotations

**Comment by HowardvanRooijen** [comment]
That's fantastic news - thanks for the fast turnaround!

**Comment by MS-TimothyMothra** [comment]
I'm going to close this issue as resolved, but if you have additional problems please feel free to reopen.
