### ISSUE TITLE
SnapshotCollector package conflicts with other versions of AppInsights

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/ApplicationInsights-Home#384]
If I create a new project and add the NuGet package `Microsoft.ApplicationInsights.SnapshotCollector` latest (1.3.5) and then try to add a dependency on `Microsoft.ApplicationInsights` (any version other than 2.4.1), I get the warning:

> Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.DependencyCollector 2.4.1 requires Microsoft.ApplicationInsights (= 2.4.0) but version Microsoft.ApplicationInsights 2.10.0 was resolved.

Future versions of the SnapshotCollector should not be tied to any specific version of ApplicationInsights. Looking through the packages, it looks like this can be solved by referencing a later version of the AppInsights.AspNetCore package such as [2.6.0](https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.6.0) or higher, instead of 2.4.0.

**Comment by TimothyMothra** [comment]
@pharring Can you forward this to the right place?

**Comment by pharring** [comment]
I think I understand. I assume you're building an ASP.NET Core 2.0 (or above) application, yes?

SnapshotCollector's dependencies are all ">=", so it shouldn't be a problem to use newer assemblies. However, one of the dependencies is Microsoft.ApplicationInsights.AspNetCore version >= 2.1.1 which brings in Microsoft.ApplicationInsights.DependencyCollector >= 2.4.1 which has an **exact match** dependency on Microsoft.ApplicationInsights = 2.4.0 (see https://www.nuget.org/packages/Microsoft.ApplicationInsights.DependencyCollector/2.4.1 and expand "Dependencies")

So, if you reference a newer base SDK (Microsoft.ApplicaitonInsights), that last dependency cannot be satisfied (hence the warning).

As far as I can tell, all versions of DependencyCollector prior to 2.9.0 are tied to an exact match version of the base SDK.

So the fix for you is to add a reference to Microsoft.ApplicationInsights.DependencyCollector 2.10.0
(and remove your direct reference on the Microsoft.ApplicationInsights base SDK).

Alternatively you could add a reference to Microsoft.ApplicationInsights.AspNetCore version 2.7.1 (which brings in DependencyCollector 2.10.0 and the corresponding base SDK).

**Comment by MisinformedDNA** [comment]
@pharring Yep, everything exactly correct. Personally, it took me "too long" to figure out what was happening, so my request was to help others avoid this issue by changing _SnapshotCollector's_ references, instead of leaving it to each developer.

**Comment by pharring** [comment]
@clguimanMSFT FYI

Glad we're on the same page. As for the remedy, I haven't decided.
We've tried to make SnapshotCollector compatible with as many versions of Application Insights as we can. I'm reluctant to forgo that compatibility.

We prompt users (via the Azure Portal) to upgrade the SnapshotCollector nuget if we detect old versions, and we could cause a problem for people stuck on older SDKs.

We could move slowly towards newer dependencies. MS.AI.AspNetCore 2.1.1 is over 2 years old now, so we could probably move to 2.2.1 or even 2.3.0 without much loss in compatibility (we'd have to monitor that).

**Comment by pharring** [comment]
[SnapshotCollector version 1.3.6 ](https://github.com/microsoft/ApplicationInsights-Home/issues/167#issuecomment-579528051) updated its dependencies.
For net45 and netstandard2.0, it now depends on SDK version 2.5.1
For netcoreapp2.0 and netcoreapp3.0 it depends on MS.AI.AspNetCore 2.2.1
That doesn't resolve this problem entirely, but it's moving in the right direction.
