### ISSUE TITLE
Application Insights duplicates

### ISSUE THREAD

**Issue by MaxiPigna** [microsoft/ApplicationInsights-Home#421]
By querying my Application Insights I found out that:
•	**Some events** are duplicated, but it doesn’t happen regularly
•	When duplication happens, **all properties are duplicated** (also itemId and timestamp)
•	It happens for **any event type**: traces, dependencies and custom events
•	Usually events are duplicated **twice**, rarely **three times**

Looking at the [Ingestion Time](https://docs.microsoft.com/en-us/azure/kusto/query/ingestiontimefunction?pivots=kusto), I got these results:
**3 duplicates scenario**
![image](https://user-images.githubusercontent.com/33937977/68303584-6a859f80-00a4-11ea-953a-282ce6167673.png)
**2 duplicates scenario**
![image](https://user-images.githubusercontent.com/33937977/68303589-6f4a5380-00a4-11ea-886f-f76760c9d543.png)

My idea is that this behavior is by design, since I observed this in 3 different applications. Maybe AI works in _at least once delivery_ mode, but I didn't find this information in the documentation. If it is like this, the assumption that itemId is unique is wrong...

**Comment by Dmitry-Matveev** [comment]
You assumption is correct. About ~3-4 years ago, Application Insights has switched from the guaranteed delivery with de-dupe it had in alpha-beta stages into "at least once delivery" mode.

However, you can try to narrow down where the duplication is happening and try to reduce it if it's under your control, such as on SDK side re-trying items due to network connection failures and similar.

Our backend team typically leverages the following guideline to understand where the duplication is happening and whether one can do something about it on SDK end:

- If you see two items with the same itemId values and different [ingestion_time()](https://docs.microsoft.com/en-us/azure/kusto/query/ingestiontimefunction?pivots=kusto) values, the duplication happened downstream from AI Endpoint.
 - If the two items have different itemId values, then the duplication happened on the client, probably because it tried re-submitting telemetry after a timeout from AI Endpoint.
