### ISSUE TITLE
Application Insights for Azure App Service preventing app start.

### ISSUE THREAD

**Issue by mbinggeli** [microsoft/ApplicationInsights-Home#422]
Dear Microsoft,

I am running a .NET Core 2.2 app in Azure and was using Application Insights.  Application Insights is now causing the app to fail on start-up.  When reviewing the logs; the following error is happening:

> 
> Application: dotnet.exe
> CoreCLR Version: 4.6.28008.2
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
> 

When I review my DLLs in Kudu; the System.Diagnostics.DiagnosticSource DLL version is 4.6.24705.01.   

The  Pre-Installed Site Extension is version 2.8.26.131.

The only way to keep my application working is to disable App Insights. As soon as I try and re-enable; it crashes the app by referencing that older version. 

Thank you for your help.

**Comment by wis3guy** [comment]
I'm experiencing the exact same problem. It all started approximately 2 weeks ago. What frustrates me most is that i can redeploy (via ftp) the site to a fresh App Service and have everything working.

**Comment by wis3guy** [comment]
# Problem description

- dotnetcoreap2.1
- existing App Service
- Application Insights enabled through the portal
- deployment through Azure DevOps

Result when accessing the site: `HTTP Error 502.5 - Process Failure`

Underlying exception, taken from `eventlog.xml`:

```
<Event>
    <System>
        <Provider Name=".NET Runtime"/>
        <EventID>1026</EventID>
        <Level>1</Level>
        <Task>0</Task>
        <Keywords>Keywords</Keywords>
        <TimeCreated SystemTime="2019-11-13T10:23:51Z"/>
        <EventRecordID>-1187543562</EventRecordID>
        <Channel>Application</Channel>
        <Computer>RD00155D058A16</Computer>
        <Security/>
    </System>
    <EventData>
        <Data>Application: dotnet.exe
CoreCLR Version: 4.6.28008.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.4.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetry(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ApplicationInsightsWebHostBuilderExtensions.&lt;&gt;c.&lt;UseApplicationInsights&gt;b__0_0(IServiceCollection collection)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.&lt;&gt;c__DisplayClass10_0.&lt;ConfigureServices&gt;b__0(WebHostBuilderContext _, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException&amp; hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at MyWebApp.Program.Main(String[] args) in /home/vsts/work/r1/a/_backend/drop/src/dotnet/MyWebApp/Program.cs:line 17
        </Data>
    </EventData>
</Event>
```

Strangely, there is an assembly, named `System.Diagnostics.DiagnosticSource.dll` in the wwwroot, but apparently it is not the version that the injected Application insights needs. Note that this assembly is part of the deployed binaries, but apparently not of the expected version.

**NB** The setup used to work and stopped working during the last week of October 2019.

## Fix 1 - Disable Application Insights for dotnet core

![disable-application-insights-for-core](https://user-images.githubusercontent.com/6885003/68760302-d078a680-0611-11ea-921d-ecc4db67f416.png)

Obvious downside is that there will be no logging to Application Insight whatsoever.

## Fix 2 - Install the Application Insights nuget package

Changing the code so that the web project references the `Microsoft.ApplicationInsights.AspNetCore` nuget package solves the problem. 

It is not required to do the actual [integration in code](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core) as described on the MSDN page.

**NB** Despite the fix, it has happened that the site still would not start after deplyment from the release pipeline. In those cases, disabling and reenabling Application Insights as described in Fix 1 solves the problem.

For now, this seems to be the best achievable outcome.

**Comment by cijothomas** [comment]
https://github.com/microsoft/ApplicationInsights-Home/blob/master/app-insights-web-app-extensions-releasenotes.md#2826
This is already addressed and being rolled out.
