### ISSUE TITLE
AddSnapshotCollector not found in IServiceCollection

### ISSUE THREAD

**Issue by bobingham** [microsoft/ApplicationInsights-Home#453]
I am running AspNetCore 2.2.0 on aspnet framework 4.6.1.
I have downloaded the the nuget package and added the following using statement to my _Startup.cs_:

`
using Microsoft.ApplicationInsights.SnapshotCollector
`

When I attempt to add the snapshot collector to my services I am getting the following error:
![image](https://user-images.githubusercontent.com/6200331/73597391-680bd800-4523-11ea-9190-5afe2cc8d34f.png)
Is this a framework problem?  I have tried downgrading to 1.3.5 with the same results.

**Comment by TimothyMothra** [comment]
@pharring Can you please take a look at this?

**Comment by pharring** [comment]
@bobingham 

The SnapshotCollector nuget has support for the following target frameworks: net45, netstandard2.0, netcoreapp2.0 and netcoreapp3.0.

The `AddSnapshotCollector` extension method is available only in the netcoreapp2.0 and netcoreapp3.0 targets.

Since you're targeting net461, your build picks the net45 target which doesn't contain that extension method.

Unfortunately, I don't know if there's a way to force it to take the "netcoreapp2.0" version (and, even if you could, it might fail in other unexpected ways).

However, the extension method is pretty simple and you can write the equivalent code yourself. The equivalent code is listed [here](https://docs.microsoft.com/azure/azure-monitor/app/snapshot-debugger-vm#configure-snapshot-collection-for-applications-using-aspnet-core-20-or-above). Follow the steps for "NuGet package version 1.3.4 or below " (3b).
You can (and should) continue to use version 1.3.6 even with this workaround. Hope that helps.

**Comment by bobingham** [comment]
Ah, so I need to implement the _SnapshotCollectorTelemetryProcessorFactory_ in my Startup and follow that method.  Thanks @pharring , I will give that a try and let you know how I get on.

**Comment by pharring** [comment]
@TimothyMothra please add the "prod:snapshot-collector" label. #prod:snapshot-collector
