### ISSUE TITLE
Could not load type 'Microsoft.ApplicationInsights.Extensibility.IContextInitializer' from assembly 'Microsoft.ApplicationInsights, Version=2.1.0.0

### ISSUE THREAD

**Issue by alextochetto** [Microsoft/ApplicationInsights-Home#50]
At the ConfigurationServices middleware of RC1-Update2 throw this exception for me at
services.AddApplicationInsightsTelemetry(Configuration);

I have the ApplicationInsights referenced in a Class Library and this Class Library is referenced at the WebApi project.

**Comment by abaranch** [comment]
Could you please ask this question here: https://github.com/Microsoft/ApplicationInsights-aspnetcore

**Comment by dnduffy** [comment]
Please upgrade to the release 1.0.0 version.

**Comment by alextochetto** [comment]
@dnduffy do you know this problem? It´s a real problem? upgrade to 1.0.0 it´s not a option right now, sorry.

**Comment by dnduffy** [comment]
IContextInitializer was removed from the Microsoft.ApplicationInsights core SDK in 2.0.0-beta2.
You appear to have mismatched assembly versions if you are trying to use 2.1.0 of the core SDK along with RC1 of AspNetCore.  Now that ASP.NET Core 1.0.0 has shipped we no longer support DNX and older RC's from the ASP.NET team (because they don't support them).
