### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by floekke** [Microsoft/ApplicationInsights-Home#54]
When running the script I'm getting:

Invoke a web request for https://aigs1.aisvc.visualstudio.com/applications/VTMBroker/Annotations?api-version=2015-11 to create a new release annotation. Attempting 1
Invoke a web request for https://aigs1.aisvc.visualstudio.com/applications/VTMBroker/Annotations?api-version=2015-11 to create a new release annotation. Attempting 2
Invoke a web request for https://aigs1.aisvc.visualstudio.com/applications/VTMBroker/Annotations?api-version=2015-11 to create a new release annotation. Attempting 3
Invoke a web request for https://aigs1.aisvc.visualstudio.com/applications/VTMBroker/Annotations?api-version=2015-11 to create a new release annotation. Attempting 4
Invoke a web request for https://aigs1.aisvc.visualstudio.com/applications/VTMBroker/Annotations?api-version=2015-11 to create a new release annotation. Attempting 5
Failed to create an annotation with Id: 4d02fd92-2805-4e67-8d0c-b9bd553ed804. Error 500, Description: Internal Server Error.
At C:\Users\FRSKL\azure\CreateReleaseAnnotation.ps1:136 char:3
+      throw $output
+      ~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to creat...l Server Error.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to create an annotation with Id: 4d02fd92-2805-4e67-8d0c-b9bd553ed804. Error 500, Description: Internal Server Error.

**Comment by SergeyKanzhelev** [comment]
cc: @jpiyali, @abgreg

**Comment by barustum** [comment]
I'll investigate

**Comment by barustum** [comment]
Hey floekke,

I believe you are not using the correct PowerShell command to create the release annotation. Here's the command:
.\CreateReleaseAnnotation.ps1 -applicationId "<appId>" -apiKey "<apiKey>" -releaseName "<releaseName>" -releaseProperties @{"ReleaseDescription"="Release with annotation";"TriggerBy"="John Doe"} -eventDateTime "2016-07-07T06:23:44"

For appId, I think you are using the name of the application, rather than the unique GUID that identifies your application. You can get the GUID for your application from the API Access blade. Please take a look at the attached picture.
![appid](https://cloud.githubusercontent.com/assets/8902531/17183940/9df2b5e0-53de-11e6-90c8-952f24fc1c52.png)

You can also use the same blade to generate an apiKey that is used when creating release annotations. More details in this link:
https://azure.microsoft.com/en-us/documentation/articles/app-insights-annotations/#get-an-api-key-from-application-insights

Please let me know if that solves your problem. If not, can you share with me the command you are using?

**Comment by floekke** [comment]
Thank you. Adding the correct applicationId and apikey did the the trick. I wasn't aware of them, only knew about the instrumentation key.

**Comment by barustum** [comment]
That's great. Let me know if you have any more issues, or if you have feedback for us :)

**Comment by lukos** [comment]
I know this was closed but the error message is not very helpful and is still the same in 2019. Could it not instead return a message like "application id not found, did you accidentally use the instrumentation key?" or even just a link to a help document?
